### ISSUE TITLE
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string

### ISSUE THREAD

**Issue by athanhat** [homenotalone/homenotalone#13]
Hi, I am trying to run `homenotalone` project locally, I followed your README instructions

```bash
node --version
v18.2.0

psql -U nassos -d athome -h 127.0.0.1 -p 5434
Password for user nassos: 
psql (15.3 (Ubuntu 15.3-1.pgdg20.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

athome=# 
```

Here is my .env file

```bash
VITE_DB_URL=postgresql://nassos@localhost:5434/athome
VITE_ORIGIN=athome.com
VITE_ADMIN_PASSWORD='@h0me'
```
The database is seeded successfully and I managed to connect using `pgPromise` node.js library
```typescript
import pgPromise from 'pg-promise';

// Create an instance of pg-promise
const pgp = pgPromise()

// connection string:
const cn = 'postgresql://nassos:@h0me@localhost:5434/athome'

// Creating a new database instance from the connection details:
const db = pgp(cn);

// psql -U nassos -d athome -h 127.0.0.1 -p 5434

db.connect()
    .then(obj => {
        // Can check the server version here (pg-promise v10.1.0+):
        const serverVersion = obj.client.serverVersion;
        const cp = obj.client.connectionParameters;

        console.log(serverVersion)
        console.log('Connected to database:', cp.database);  
        
        obj.done(); // success, release the connection;
    })
    .catch(error => {
        console.log('ERROR:', error.message || error);
});
```

```bash
15.3 (Ubuntu 15.3-1.pgdg20.04+1)
Connected to database: athome
```

I have installed successfully dependencies `pnpm i`

and started a development server but I am getting the following error when I try to access the home page of the web site.

```bash
 pnpm dev

> editable-home@0.0.1 dev /home/athan/Work/TestSvelte/homenotalone
> vite dev

@vavite/node-loader/plugin: @vavite/node-loader is not enabled. Please run with `node --experimental-loader=@vavite/node-loader`.


  VITE v4.2.0  ready in 769 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
    at Object.continueSession (/home/athan/Work/TestSvelte/homenotalone/node_modules/.pnpm/pg@8.11.0/node_modules/pg/lib/crypto/sasl.js:24:11)
    at Client._handleAuthSASLContinue (/home/athan/Work/TestSvelte/homenotalone/node_modules/.pnpm/pg@8.11.0/node_modules/pg/lib/client.js:272:18)
    at Connection.emit (node:events:527:28)
    at /home/athan/Work/TestSvelte/homenotalone/node_modules/.pnpm/pg@8.11.0/node_modules/pg/lib/connection.js:117:12
    at Parser.parse (/home/athan/Work/TestSvelte/homenotalone/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/athan/Work/TestSvelte/homenotalone/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
```
Can you help me fix this and complete my test ?
Thank you

**Comment by michael** [comment]
Hmm... Is it possible that it's because no Postgres password is explicitly set in the connection string?

Maybe it needs `postgresql://nassos:xxxxxxxxx@localhost:5434/athome`?

**Comment by athanhat** [comment]
Yes, that worked, I thought `VITE_ADMIN_PASSWORD` was for postgres. It is better to update the `.env` configuration to include postgres password.
Thank you Michael
